#! /bin/bash

##
## Commands to run at first boot on the mesh-potato Pi device
##


ME=`basename $0`

echo "Running ${ME}..."

echo " *** waiting for network... ***"
sleep 5

pacman -v --noconfirm -U /root/.mesh-potato/required_packages/libnl-3.2.25-1-armv6h.pkg.tar.xz
pacman -v --noconfirm -U /root/.mesh-potato/required_packages/iw-3.17-1-armv6h.pkg.tar.xz
#pacman -v --noconfirm -U /root/.mesh-potato/required_packages/avahi-0.6.31-16-armv6h.pkg.tar.xz

/root/.mesh-potato/enable_mesh
systemctl enable mesh-potato.service

cat << EOF > $0
#! /bin/bash
echo "First boot previously completed"
systemctl disable first_boot.service
   
EOF

